.TH "pysysbot" "1" "0.0.1" "Fabian Affolter" "Jabber bot for the displaying system details"
.SH "NAME"
.LP 
pysysbot \- A python based system jabber bot
.SH "SYNTAX"
.LP 
myprogram [\fIoption\fP] <\fIfilename\fP>
.br 
myprogram \fI\-dscan\fP <\fIdirectory\fP>
.SH "DESCRIPTION"
.LP 
This python jabber (XMPP) bot is based on the jabberbot framework
(http://thpinfo.com/2007/python-jabberbot/).  The bot is capable to
display details about the system it is running on.  Currently support
load, network configuration, system time, uptime, users who are logged
on, and kernel information.
.SH "OPTIONS"
.LP 
To run this program the standard way, please type:
.LP 
python pysysbot.py
.SH "AUTHORS"
.LP 
Fabian Affolter <fabian@bernewireless.net>
.SH "SEE ALSO"
.LP 
python-jabberbot(1)
